// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzyyjxpzbbozrlpfonwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6eXlqeHB6YmJvenJscGZvbnd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzgyMzYsImV4cCI6MjA3NDMxNDIzNn0.OXqe70-aZ6gnaRbmn4eJ_-JQYYJrc_YctwToxt-Ph0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});